

DROP TABLE RESERVACIONES;
DROP TABLE ESTADOS_RESERVACIONES;
DROP TABLE HABITACIONES;
DROP TABLE TIPOS_HABITACIONES;
DROP TABLE ROLES;
DROP TABLE TIPOS_ROLES;
DROP TABLE USUARIOS; 
DROP TABLE MENSAJES_SISTEMA;  

CREATE TABLE USUARIOS
(
  ID                    NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  NOMBRES               NVARCHAR2(50)                    NOT NULL,
  APELLIDOS             NVARCHAR2(50)                    NOT NULL,
  CEDULA                CHAR(11)             UNIQUE      NOT NULL,
  TELEFONO              CHAR(10)                         NOT NULL,
  CELULAR               CHAR(10)                         NOT NULL,
  CORREO                NVARCHAR2(50)        UNIQUE      NOT NULL, 
  USUARIO               NVARCHAR2(25)        UNIQUE      NOT NULL,
  CLAVE                 NVARCHAR2(100)                   NOT NULL,
  ESTADO                NUMBER(1,0)                      NOT NULL 
);

CREATE TABLE TIPOS_ROLES
(
  ID                    NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  DESCRIPCION           NVARCHAR2(100)       UNIQUE      NOT NULL,
  ESTADO                NUMBER(1,0)                      NOT NULL 
);

CREATE TABLE ROLES
(
  ID                    NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ID_USUARIO            NUMBER,
  ID_TIPO_ROL           NUMBER,
  CONSTRAINT ID_ROLES_USUARIOS_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
  CONSTRAINT ID_ROLES_TIPO_ROL_FK FOREIGN KEY (ID_USUARIO) REFERENCES TIPOS_ROLES(ID)  
);

CREATE TABLE TIPOS_HABITACIONES
(
  ID                    NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  DESCRIPCION           NVARCHAR2(100)       UNIQUE      NOT NULL,
  ESTADO                NUMBER(1,0)                      NOT NULL 
);

CREATE TABLE HABITACIONES
(
  ID                    NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ID_TIPO_HABITACION    NUMBER,
  PRECIO_POR_NOCHE      NUMBER(8,2)                      NOT NULL,
  CANT_MAX_PERSONAS     NUMBER(1,0)                      NOT NULL,
  ESTADO                NUMBER(1,0)                      NOT NULL,
 CONSTRAINT ID_TIPO_HABITACION_FK FOREIGN KEY (ID_TIPO_HABITACION) REFERENCES TIPOS_HABITACIONES(ID)
);

CREATE TABLE ESTADOS_RESERVACIONES
(
  ID                    NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  DESCRIPCION           NVARCHAR2(100)       UNIQUE      NOT NULL,
  ESTADO                NUMBER(1,0)                      NOT NULL 
);

CREATE TABLE RESERVACIONES
(
  ID                    NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ID_HABITACION         NUMBER,
  ID_ESTADO             NUMBER,
  ID_USUARIO            NUMBER,
  FECHA_DESDE           DATE                             NOT NULL,
  FECHA_HASTA           DATE                             NOT NULL,
  MONTO_ESTADIA         NUMBER(8,2)                      NOT NULL,
  CONSTRAINT ID_HABITACION_FK FOREIGN KEY (ID_HABITACION) REFERENCES HABITACIONES(ID), 
  CONSTRAINT ID_ESTADO_FK     FOREIGN KEY (ID_ESTADO)     REFERENCES ESTADOS_RESERVACIONES(ID), 
  CONSTRAINT ID_USUARIO_FK    FOREIGN KEY (ID_USUARIO)    REFERENCES USUARIOS(ID)
);

CREATE TABLE MENSAJES_SISTEMA
(
    ID              	NUMBER  GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    DESCRIPCION     	NVARCHAR2(200)       UNIQUE        NOT NULL
);

